src/Glpi/Form/Form.php
<?php

/**
 * ---------------------------------------------------------------------
 *
 * GLPI - Gestionnaire Libre de Parc Informatique
 *
 * http://glpi-project.org
 *
 * @copyright 2015-2025 Teclib' and contributors.
 * @copyright 2003-2014 by the INDEPNET Development Team.
 * @licence   https://www.gnu.org/licenses/gpl-3.0.html
 *
 * ---------------------------------------------------------------------
 *
 * LICENSE
 *
 * This file is part of GLPI.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * ---------------------------------------------------------------------
 */

namespace Glpi\Form;

use AbstractRightsDropdown;
use Change_Item;
use CommonDBTM;
use CommonGLPI;
use CronTask;
use Entity;
use Glpi\Application\View\TemplateRenderer;
use Glpi\DBAL\QuerySubQuery;
use Glpi\Features\Clonable;
use Glpi\Form\AccessControl\ControlType\AllowList;
use Glpi\Form\AccessControl\ControlType\AllowListConfig;
use Glpi\Form\AccessControl\ControlType\ControlTypeInterface;
use Glpi\Form\AccessControl\FormAccessControl;
use Glpi\Form\AccessControl\FormAccessControlManager;
use Glpi\Form\Clone\FormCloneHelper;
use Glpi\Form\Condition\CommentData;
use Glpi\Form\Condition\ConditionableVisibilityInterface;
use Glpi\Form\Condition\ConditionableVisibilityTrait;
use Glpi\Form\Condition\FormData;
use Glpi\Form\Condition\QuestionData;
use Glpi\Form\Condition\SectionData;
use Glpi\Form\Destination\FormDestination;
use Glpi\Form\Destination\FormDestinationTicket;
use Glpi\Form\QuestionType\QuestionTypeInterface;
use Glpi\Form\QuestionType\QuestionTypesManager;
use Glpi\Form\ServiceCatalog\ServiceCatalog;
use Glpi\Form\ServiceCatalog\ServiceCatalogLeafInterface;
use Glpi\Helpdesk\Tile\FormTile;
use Glpi\ItemTranslation\Context\ProvideTranslationsInterface;
use Glpi\ItemTranslation\Context\TranslationHandler;
use Glpi\Toolbox\UuidStore;
use Glpi\UI\IllustrationManager;
use Html;
use InvalidArgumentException;
use Item_Problem;
use Item_Ticket;
use Log;
use MassiveAction;
use Override;
use Ramsey\Uuid\Uuid;
use ReflectionClass;
use RuntimeException;
use Session;
use Throwable;
use Ticket;

use function Safe\json_decode;
use function Safe\json_encode;
use function Safe\strtotime;

/**
 * Helpdesk form
 */
final class Form extends CommonDBTM implements
    ServiceCatalogLeafInterface,
    ProvideTranslationsInterface,
    ConditionableVisibilityInterface
{
    use ConditionableVisibilityTrait;
    use Clonable {
        Clonable::prepareInputForClone as parentPrepareInputForClone;
        Clonable::post_clone as parentPostClone;
    }

    public const TRANSLATION_KEY_NAME = 'form_name';
    public const TRANSLATION_KEY_HEADER = 'form_header';
    public const TRANSLATION_KEY_DESCRIPTION = 'form_description';

    public static $rightname = 'form';

    public $dohistory = true;

    public $history_blacklist = [
        'date_mod',
    ];

    /**
     * Lazy loaded array of sections
     * Should always be accessed through getSections()
     * @var Section[]|null
     */
    private ?array $sections = null;

    /** @var ?FormAccessControl[] */
    private ?array $access_controls = null;

    #[Override]
    public static function getTypeName($nb = 0)
    {
        return _n('Form', 'Forms', $nb);
    }

    #[Override]
    public function getUUID(): string
    {
        return $this->fields['uuid'];
    }

    #[Override]
    public static function getIcon()
    {
        return "ti ti-forms";
    }

    #[Override]
    public static function getSectorizedDetails(): array
    {
        return ['admin', self::class];
    }

    #[Override]
    public function defineTabs($options = [])
    {
        $tabs = parent::defineTabs();
        $this->addStandardTab(ServiceCatalog::class, $tabs, $options);
        if (Item_Ticket::countForItemAndLinked($this) > 0) {
            $this->addStandardTab(Item_Ticket::class, $tabs, $options);
        }
        if (Change_Item::countForItemAndLinked($this) > 0) {
            $this->addStandardTab(Change_Item::class, $tabs, $options);
        }
        if (Item_Problem::countForItemAndLinked($this) > 0) {
            $this->addStandardTab(Item_Problem::class, $tabs, $options);
        }
        $this->addStandardTab(FormAccessControl::class, $tabs, $options);
        $this->addStandardTab(FormDestination::class, $tabs, $options);
        $this->addStandardTab(FormTranslation::class, $tabs, $options);
        $this->addStandardTab(Log::class, $tabs, $options);
        $tabs['no_all_tab'] = true;
        return $tabs;
    }

    #[Override]
    public function showForm($id, array $options = [])
    {
        if (!empty($id)) {
            $this->getFromDB($id);
        } else {
            $this->getEmpty();
        }
        $this->initForm($id, $options);

        $types_manager = QuestionTypesManager::getInstance();

        // Use the uuid store to prevent condition data from fetching the same
        // questions over and over
        $store = UuidStore::getInstance();
        foreach ($this->getSections() as $section) {
            $store->addToStore($section->fields['uuid'], $section);
        }
        foreach ($this->getQuestions() as $question) {
            $store->addToStore($question->fields['uuid'], $question);
        }
        foreach ($this->getFormComments() as $comment) {
            $store->addToStore($comment->fields['uuid'], $comment);
        }

        // Render twig template
        $twig = TemplateRenderer::getInstance();
        $twig->display('pages/admin/form/form_editor.html.twig', [
            'item'                         => $this,
            'can_update'                   => $this->canUpdate(),
            'params'                       => $options,
            'question_types_manager'       => $types_manager,
            'invalid_questions'            => $this->getInvalidQuestions(),
            'allow_unauthenticated_access' => FormAccessControlManager::getInstance()->allowUnauthenticatedAccess($this),
        ]);
        $store->purge();
        return true;
    }

    #[Override]
    public function getTabNameForItem(CommonGLPI $item, $withtemplate = 0): string
    {
        if (!$item instanceof Category) {
            return "";
        }

        $nb = 0;
        if ($_SESSION['glpishow_count_on_tabs']) {
            $nb = countElementsInTable(self::getTable(), [
                'forms_categories_id' => $item->getID(),
            ]);
        }

        return self::createTabEntry(
            self::getTypeName(Session::getPluralNumber()),
            $nb,
        );
    }

    #[Override]
    public static function displayTabContentForItem(
        CommonGLPI $item,
        $tabnum = 1,
        $withtemplate = 0
    ): bool {
        if (!$item instanceof Category) {
            return false;
        }

        self::displayList([
            [
                'link'       => 'AND',
                'field'      => 6,  // Service catalog category
                'searchtype' => 'equals',
                'value'      => $item->getID(),
            ],
        ], 1 /* Sort by name */);
        return true;
    }

    #[Override]
    public function rawSearchOptions()
    {
        $search_options = parent::rawSearchOptions();

        $search_options[] = [
            'id'            => '2',
            'table'         => self::getTable(),
            'field'         => 'id',
            'name'          => __('ID'),
            'massiveaction' => false,
            'datatype'      => 'number',
        ];
        $search_options[] = [
            'id'            => '80',
            'table'         => Entity::getTable(),
            'field'         => 'completename',
            'name'          => Entity::getTypeName(1),
            'datatype'      => 'dropdown',
            'massiveaction' => false,
        ];
        $search_options[] = [
            'id'       => '3',
            'table'    => $this->getTable(),
            'field'    => 'is_active',
            'name'     => __('Active'),
            'datatype' => 'bool',
        ];
        $search_options[] = [
            'id'            => '4',
            'table'         => $this->getTable(),
            'field'         => 'date_mod',
            'name'          => __('Last update'),
            'datatype'      => 'datetime',
            'massiveaction' => false,
        ];
        $search_options[] = [
            'id'            => '5',
            'table'         => $this->getTable(),
            'field'         => 'date_creation',
            'name'          => __('Creation date'),
            'datatype'      => 'datetime',
            'massiveaction' => false,
        ];
        $search_options[] = [
            'id'            => '6',
            'table'         => Category::getTable(),
            'field'         => 'completename',
            'name'          => Category::getTypeName(1),
            'datatype'      => 'dropdown',
            'massiveaction' => true,
        ];

        return $search_options;
    }

    #[Override]
    public function post_getFromDB()
    {
        // Clear lazy loaded data
        $this->clearLazyLoadedData();
    }

    #[Override]
    public function post_addItem()
    {
        $from_import    = $this->input['_from_import']    ?? false;
        $from_migration = $this->input['_from_migration'] ?? false;
        if ($from_import || $from_migration) {

src/Glpi/Controller/CentralController.php
<?php

/**
 * ---------------------------------------------------------------------
 *
 * GLPI - Gestionnaire Libre de Parc Informatique
 *
 * http://glpi-project.org
 *
 * @copyright 2015-2025 Teclib' and contributors.
 * @licence   https://www.gnu.org/licenses/gpl-3.0.html
 *
 * ---------------------------------------------------------------------
 *
 * LICENSE
 *
 * This file is part of GLPI.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * ---------------------------------------------------------------------
 */

namespace Glpi\Controller;

use Central;
use Glpi\Dashboard\Grid;
use Glpi\Http\Firewall;
use Glpi\Http\RedirectResponse;
use Glpi\Security\Attribute\SecurityStrategy;
use Session;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Toolbox;

class CentralController extends AbstractController
{
    #[Route('/front/central.php', name: 'front_central_legacy')]
    #[Route('/Central', name: 'front_central')]
    #[SecurityStrategy(Firewall::STRATEGY_NO_CHECK)] // No automatic check, to allow embed dashboards
    public function __invoke(Request $request): Response
    {
        if ($request->query->has('embed') && $request->query->has('dashboard')) {
            // embed (anonymous) dashboard
            $grid = new Grid($request->query->get('dashboard'));
            $grid->initEmbed($request->query->all());

            return $this->render('central/embed_dashboard.html.twig', [
                'grid'  => $grid,
                'token' => $request->query->get('token'),
            ]);
        }

        Session::checkCentralAccess();

        if (
            $request->query->has('redirect')
            && $url = Toolbox::computeRedirect($request->query->get('redirect'))
        ) {
            return new RedirectResponse($url);
        }

        return $this->render('pages/central/index.html.twig', [
            'central' => new Central(),
        ]);
    }
}

templates/central/lists/itemtype_count.html.twig
{#
 # ---------------------------------------------------------------------
 #
 # GLPI - Gestionnaire Libre de Parc Informatique
 #
 # http://glpi-project.org
 #
 # @copyright 2015-2025 Teclib' and contributors.
 # @licence   https://www.gnu.org/licenses/gpl-3.0.html
 #
 # ---------------------------------------------------------------------
 #
 # LICENSE
 #
 # This file is part of GLPI.
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #
 # ---------------------------------------------------------------------
 #}

{% macro link_or_text(value, anchor_class = '') %}
   {% if value.link is defined %}
      <a class="{{ anchor_class }}" href="{{ value.link }}">
   {% endif %}
         <span>
            {% if value.icon is defined %}
               <i class="{{ value.icon }}"></i>
            {% endif %}
            {{ value.text }}
         </span>
         {% if value.count is defined %}
            <span class="badge bg-secondary text-secondary-fg">{{ value.count }}</span>
         {% endif %}
   {% if value.link is defined %}
      </a>
   {% endif %}
{% endmacro %}

<div class="card">
   <div class="card-body">
      <div class="card-title d-flex justify-content-between">
         {{ _self.link_or_text(title) }}

         {% if title.button is defined %}
            {{ _self.link_or_text(title.button, 'btn btn-sm btn-outline-secondary') }}
         {% endif %}
      </div>

      {% if subtitle is defined %}
         <div class="card-subtitle">
            {{ _self.link_or_text(subtitle) }}
         </div>
      {% endif %}
   </div>


   <ul class="list-group list-group-flush">
      {% for item in items %}
         {{ _self.link_or_text(item, 'list-group-item list-group-item-action d-flex justify-content-between align-items-center') }}
      {% endfor %}
   </ul>
</div>

templates/central/lists/table.html.twig
{#
 # ---------------------------------------------------------------------
 #
 # GLPI - Gestionnaire Libre de Parc Informatique
 #
 # http://glpi-project.org
 #
 # @copyright 2015-2025 Teclib' and contributors.
 # @licence   https://www.gnu.org/licenses/gpl-3.0.html
 #
 # ---------------------------------------------------------------------
 #
 # LICENSE
 #
 # This file is part of GLPI.
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #
 # ---------------------------------------------------------------------
 #}

{% set superheader_row %}
    <div class="relative">
        <span>{{ title|raw }}</span>
        <span class="float-end">
            {% if add_link is not empty %}
                <a href="{{ add_link }}" title="{{ __('Add') }}">
                    <i class="ti ti-plus"></i>
                </a>
            {% endif %}
        </span>
    </div>
{% endset %}

{% set superheader_colspan = rows is not empty ? rows[0]['values']|length : 1 %}

{% include('components/table.html.twig') with {
    class: 'table table-striped card-table table-hover',
    header_rows: [
        [{
            colspan: superheader_colspan,
            content: superheader_row,
        }]
    ]|merge(header_rows|default([])),
    rows: rows,
} only %}